name: clearvpn
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.12.2
  permission_handler: ^10.0.0
  path_provider: ^2.0.14
  flutter_screenutil: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vpn/franceclient.ovpn
    - assets/vpn/openvpn
    - assets/vpn/vpn_credentials.txt

